name: sweet_planner
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.4
  logger: ^2.0.2+1
  flutter_bloc: ^8.1.5
  gap: ^3.0.1
  get_it: ^7.7.0
  equatable: ^2.0.5
  inner_glow: ^1.0.0
  shared_preferences: ^2.3.1
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_spinkit: ^5.2.1
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.1.2
  advertising_id: ^2.7.1
  printing: ^5.13.4
  pdf: ^3.11.1
  uuid: ^4.5.1
  step_progress_indicator: ^1.0.2
  flutter_svg: ^2.0.10+1
  path_provider: ^2.1.5
  share_plus: ^10.1.2
  flutter_advanced_switch: ^3.1.0
  core_logic:
    git:
      url: https://github.com/Vennylost/core_logic.git
      ref: bc4cf0be04e314ac1ed93bdc08d741753bd79819

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true
  assets:
     - assets/
     - assets/images/
     - assets/fonts/
     - assets/json/
     - assets/generated/

  fonts:
    - family: Boleh
      fonts:
        - asset: assets/fonts/Boleh.ttf
    - family: Cygre Black
      fonts:
        - asset: assets/fonts/Cygre.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
     


